// shop_site_fe/src/components/pages/segments/Header.jsx
import React, { useState } from 'react';
import Listing from '../../modals/patron-modals/Listing';
import Search from '../../modals/patron-modals/Search';
import Backdrop from '../../../utils/backdrop';
import menu from '../../../utils/images/header/hamburger-menu.png';
import account from '../../../utils/images/header/profile-.png';
import searchIcon from '../../../utils/images/header/search-icon.png';
import cart from '../../../utils/images/header/cart-.png';
import heart from '../../../utils/images/header/fav-heart.png';
import '../../../styles/pages/segemnts/header.scss';

const Header = ({ onSearch }) => {
    const [listing, showListing] = useState(false);
    const [searching, showSearching] = useState(false);
    const [search, setSearch] = useState('');

    const handleChange = (e) => {
        setSearch(e.target.value);
    };

    const handleSubmit = (e) => {
        e.preventDefault();
        if (onSearch) {
            onSearch(search.trim());
        }
        showSearching(false);
    };

    return (
        <div className='header'>
            <div className="listingbtn" onClick={() => showListing(true)}>
                {listing ? (
                    <div>
                        <Listing />
                        <Backdrop show={listing} set={showListing} />
                    </div>
                ) : (
                    <img className="menu header-link" src={menu} alt="menu" />
                )}
            </div>
            <h1 className='title'>Decorem</h1>
            <div className='optionalbtn'>
                <div className="searchbtn" onClick={() => showSearching(true)}>
                    {searching ? (
                        <div>
                            <Search
                                search={search}
                                handleChange={handleChange}
                                handleSubmit={handleSubmit}
                                showSearching={showSearching}
                            />
                            <Backdrop show={searching} set={showSearching} />
                        </div>
                    ) : (
                        <img className="search-bar header-link" src={searchIcon} alt="search-bar" />
                    )}
                </div>
                <img className="cartpic header-link" src={cart} alt="cart" />
                <img className="favs header-link" src={heart} alt="favorites" />
                <img className="account header-link" src={account} alt="account" />
            </div>
        </div>
    );
};

export default Header;

// decorem/src/components/pages/segments/Header.vue
<template>
  <header>
    <div v-if="browsingItems == true">
          <Listing />
          <!-- <Backdrop show='browsing' set={showListing} /> -->
    </div> 
    <img class="header-link" :src="menu" alt="menu" />
    <h1>{{ title }}</h1>
        <div v-if="searchingItems == true">
          <SearchBar />
          <!-- <Backdrop show='browsing' set={showListing} /> -->
    </div> 
    <img class="header-link" :src="searchIcon" alt="magnifing-glass" />
        <div v-if="savingItems == true">
          <SavedList />
          <!-- <Backdrop show='browsing' set={showListing} /> -->
    </div> 
    <img class="header-link" :src="heart" alt="heart" />
        <div v-if="cartingItems == true">
          <Cart />
          <!-- <Backdrop show='browsing' set={showListing} /> -->
    </div> 
    <img class="header-link" :src="cart" alt="cart" />
        <div v-if="profiling == true">
          <Profile />
          <!-- <Backdrop show='browsing' set={showListing} /> -->
    </div> 
    <img class="header-link" :src="account" alt="silhouette" />
  </header>
</template>

<script>
import Listing from '../../modals/patron-modals/Listing.vue';
import SearchBar from '../../modals/patron-modals/SearchBar.vue';
import SavedList from '../../modals/patron-modals/SavedList.vue';
import Cart from '../../modals/patron-modals/Cart.vue';
import Profile from '../../modals/patron-modals/Profile.vue';
// import Backdrop from '../../../utils/backdrop.vue';
import menu from '../../../utils/images/header/hamburger-menu.png';
import account from '../../../utils/images/header/profile-.png';
import searchIcon from '../../../utils/images/header/search-icon.png';
import cart from '../../../utils/images/header/cart-.png';
import heart from '../../../utils/images/header/fav-heart.png';

export default {
  name: 'Header',
  props: {
      title: String,
      browsingItems: Boolean,
      searchingItems: Boolean,
      savingItems: Boolean,
      cartingItems: Boolean,
      profiling: Boolean,
  },
  data() {
    return {
      menu: menu,
      account: account,
      searchIcon: searchIcon,
      cart: cart,
      heart: heart,
    }
  },
  components: {
      Listing,
      SearchBar,
      SavedList,
      Cart,
      Profile,
      // Backdrop,
  },
}
</script>

<style scoped>
header {
  display: flex;
  justify-content: space-around;
  align-items: center;
  margin-bottom: 20px;
}

.header-link {
    height: 1.5em;
    width: 1.5em;  
}
</style>
